version: '3.8'
services:
  api:
    build: .
    image: postapi
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/app:ro
    command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password123
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
